INSERT INTO "whitedeck"( wcvalue) VALUES
( 'A Gypsy curse.' ),
( 'A moment of silence.' ),
( 'A sausage festival.' ),
( 'An honest cop with nothing left to lose.' ),
( 'Famine.' ),
( 'Flesh-eating bacteria.' ),
( 'Flying sex snakes.' ),
( 'Not giving a shit about the Third World.' ),
( 'Sexting.' ),
( 'Shapeshifters.' ),
( 'Porn stars.' ),
( '72 virgins.' ),
( 'A drive-by shooting.' ),
( 'A time travel paradox.' ),
( 'Authentic Mexican cuisine.' ),
( 'Bling.' ),
( 'Consultants.' ),
( 'Crippling debt.' ),
( 'Daddy issues.' ),
( 'The Donald Trump Seal of Approval™.' ),
( 'Dropping a chandelier on your enemies and riding the rope up.' ),
( 'Former President George W. Bush.' ),
( 'Full frontal nudity.' ),
( 'Hormone injections.' ),
( 'Laying an egg.' ),
( 'Getting naked and watching Nickelodeon.' ),
( 'Pretending to care.' ),
( 'Public ridicule.' ),
( 'Sharing needles.' ),
( 'Boogers.' ),
( 'The inevitable heat death of the universe.' ),
( 'The miracle of childbirth.' ),
( 'The Rapture.' ),
( 'Whipping it out.' ),
( 'White privilege.' ),
( 'Wifely duties.' ),
( 'The Hamburglar.' ),
( 'AXE Body Spray.' ),
( 'The Blood of Christ.' ),
( 'Horrifying laser hair removal accidents.' ),
( 'BATMAN!!!' ),
( 'Agriculture.' ),
( 'A robust mongoloid.' ),
( 'Natural selection.' ),
( 'Coat hanger abortions.' ),
( 'Eating all of the cookies before the AIDS bake-sale.' ),
( 'Michelle Obama`s arms.' ),
( 'The World of Warcraft.' ),
( 'Swooping.' ),
( 'Obesity.' ),
( 'A homoerotic volleyball montage.' ),
( 'Lockjaw.' ),
( 'A mating display.' ),
( 'All-you-can-eat shrimp for $4.99.' ),
( 'Domino`s™ Oreo™ Dessert Pizza.' ),
( 'Kanye West.' ),
( 'Hot cheese.' ),
( 'Raptor attacks.' ),
( 'Taking off your shirt.' ),
( 'Alcoholism.' ),
( 'A middle-aged man on roller skates.' ),
( 'The Care Bear Stare.' ),
( 'Bingeing and purging.' ),
( 'Oversized lollipops.' ),
( 'Self-loathing.' ),
( 'Children on leashes.' ),
( 'The Holy Bible.' ),
( 'German dungeon porn.' ),
( 'Being on fire.' ),
( 'Teenage pregnancy.' ),
( 'Gandhi.' ),
( 'Leaving an awkward voicemail.' ),
( 'Uppercuts.' ),
( 'Customer service representatives.' ),
( 'Picking up girls at the abortion clinic.' ),
( 'Science.' ),
( 'Flightless birds.' ),
( 'A good sniff.' ),
( 'Waterboarding.' ),
( 'A balanced breakfast.' ),
( 'Historically black colleges.' ),
( 'Actually taking candy from a baby.' ),
( 'The Make-A-Wish Foundation.' ),
( 'A clandestine butt scratch.' ),
( 'Passive-aggressive Post-it notes.' ),
( 'The Chinese gymnastics team.' ),
( 'Switching to Geico.' ),
( 'Peeing a little bit.' ),
( 'Home video of Oprah sobbing into a Lean Cuisine.' ),
( 'Nocturnal emissions.' ),
( 'The Jews.' ),
( 'My humps.' ),
( 'Powerful thighs.' ),
( 'Winking at old people.' ),
( 'Mr. Clean, right behind you.' ),
( 'A gentle caress of the inner thigh.' ),
( 'Sexual tension.' ),
( 'The forbidden fruit.' ),
( 'Skeletor.' ),
( 'Fancy Feast.' ),
( 'Being rich.' ),
( 'Sweet, sweet vengeance.' ),
( 'Republicans.' ),
( 'A gassy antelope.' ),
( 'Natalie Portman.' ),
( 'Copping a feel.' ),
( 'Kamikaze pilots.' ),
( 'Sean Connery.' ),
( 'The homosexual agenda.' ),
( 'The hardworking Mexican.' ),
( 'A falcon with a cap on its head.' ),
( 'Altar boys.' ),
( 'The Kool-Aid Man.' ),
( 'Free samples.' ),
( 'A big hoopla about nothing.' ),
( 'Doing the right thing.' ),
( 'The Three-Fifths compromise.' ),
( 'Lactation.' ),
( 'World peace.' ),
( 'RoboCop.' ),
( 'Chutzpah.' ),
( 'Justin Bieber.' ),
( 'Oompa-Loompas.' ),
( 'Inappropriate yodeling.' ),
( 'Puberty.' ),
( 'Ghosts.' ),
( 'Vigorous jazz hands.' ),
( 'GoGurt.' ),
( 'Police brutality.' ),
( 'John Wilkes Booth.' ),
( 'Preteens.' ),
( 'Scalping.' ),
( 'Stifling a giggle at the mention of Hutus and Tutsis.' ),
( '“Tweeting”.' ),
( 'Darth Vader.' ),
( 'Exactly what you`d expect.' ),
( 'Expecting a burp and vomiting on the floor.' ),
( 'Adderall™.' ),
( 'Embryonic stem cells.' ),
( 'Panda sex.' ),
( 'An icepick lobotomy.' ),
( 'Tom Cruise.' ),
( 'Mouth herpes.' ),
( 'Sperm whales.' ),
( 'Homeless people.' ),
( 'Third base.' ),
( 'Incest.' ),
( 'A mime having a stroke.' ),
( 'Hulk Hogan.' ),
( 'God.' ),
( 'Scrubbing under the folds.' ),
( 'Emotions.' ),
( 'Licking things to claim them as your own.' ),
( 'Pabst Blue Ribbon.' ),
( 'The placenta.' ),
( 'Spontaneous human combustion.' ),
( 'Friends with benefits.' ),
( 'Finger painting.' ),
( 'Old-people smell.' ),
( 'Dying of dysentery.' ),
( 'My inner demons.' ),
( 'A Super Soaker™ full of cat pee.' ),
( 'Aaron Burr.' ),
( 'Cuddling.' ),
( 'The chronic.' ),
( 'Friendly fire.' ),
( 'Ronald Reagan.' ),
( 'A disappointing birthday party.' ),
( 'A sassy black woman.' ),
( 'Mathletes.' ),
( 'A tiny horse.' ),
( 'William Shatner.' ),
( 'Riding off into the sunset.' ),
( 'An M. Night Shyamalan plot twist.' ),
( 'Jew-fros.' ),
( 'Mutually-assured destruction.' ),
( 'Pedophiles.' ),
( 'Yeast.' ),
( 'Grave robbing.' ),
( 'Eating the last known bison.' ),
( 'Catapults.' ),
( 'Poor people.' ),
( 'Forgetting the Alamo.' ),
( 'The Hustle.' ),
( 'The Force.' ),
( 'Intelligent design.' ),
( 'Loose lips.' ),
( 'AIDS.' ),
( 'The Übermensch.' ),
( 'Sarah Palin.' ),
( 'American Gladiators.' ),
( 'Getting really high.' ),
( 'Scientology.' ),
( 'Praying the gay away.' ),
( 'Frolicking.' ),
( 'The KKK.' ),
( 'Genghis Khan.' ),
( 'Crystal meth.' ),
( 'Serfdom.' ),
( 'Stranger danger.' ),
( 'A Bop It™.' ),
( 'Shaquille O`Neal`s acting career.' ),
( 'Prancing.' ),
( 'Vigilante justice.' ),
( 'Overcompensation.' ),
( 'A lifetime of sadness.' ),
( 'Racism.' ),
( 'Dwarf tossing.' ),
( 'Sunshine and rainbows.' ),
( 'A monkey smoking a cigar.' ),
( 'Flash flooding.' ),
( 'Dry heaving.' ),
( 'The terrorists.' ),
( 'Britney Spears at 55.' ),
( 'Attitude.' ),
( 'Breaking out into song and dance.' ),
( 'Leprosy.' ),
( 'The heart of a child.' ),
( 'Puppies!' ),
( 'Waking up half-naked in a Denny`s parking lot.' ),
( 'Dental dams.' ),
( 'The taint; the grundle; the fleshy fun-bridge.' ),
( 'Active listening.' ),
( 'Ethnic cleansing.' ),
( 'The Little Engine That Could.' ),
( 'The invisible hand.' ),
( 'Waiting ‘til marriage.' ),
( 'Unfathomable stupidity.' ),
( 'Euphoria™ by Calvin Klein.' ),
( 'Re-gifting.' ),
( 'Autocannibalism.' ),
( 'Erectile dysfunction.' ),
( 'The Pope.' ),
( 'White people.' ),
( 'Tentacle porn.' ),
( 'Too much hair gel.' ),
( 'Seppuku.' ),
( 'Same-sex ice dancing.' ),
( 'Cheating in the Special Olympics.' ),
( 'Charisma.' ),
( 'Keanu Reeves.' ),
( 'Sean Penn.' ),
( 'Nickelback.' ),
( 'A look-see.' ),
( 'Pooping back and forth. Forever.' ),
( 'Menstruation.' ),
( 'Kids with ass cancer.' ),
( 'A salty surprise.' ),
( 'The South.' ),
( 'The violation of our most basic human rights.' ),
( 'YOU MUST CONSTRUCT ADDITIONAL PYLONS.' ),
( 'Being fabulous.' ),
( 'Necrophilia.' ),
( 'Centaurs.' ),
( 'Bill Nye the Science Guy.' ),
( 'Black people.' ),
( 'Chivalry.' ),
( 'Lunchables™.' ),
( 'Bitches.' ),
( 'The profoundly handicapped.' ),
( 'Heartwarming orphans.' ),
( 'MechaHitler.' ),
( 'Fiery poops.' ),
( 'Another goddamn vampire movie.' ),
( 'Tangled Slinkys.' ),
( 'The true meaning of Christmas.' ),
( 'Estrogen.' ),
( 'A zesty breakfast burrito.' ),
( 'That thing that electrocutes your abs.' ),
( 'Passing a kidney stone.' ),
( 'Michael Jackson.' ),
( 'Cybernetic enhancements.' ),
( 'Guys who don`t call.' ),
( 'Smallpox blankets.' ),
( 'Classist undertones.' ),
( 'Queefing.' ),
( 'Edible underpants.' ),
( 'Viagra.' ),
( 'Soup that is too hot.' ),
( 'Muhammad (Praise Be Unto Him).' ),
( 'Surprise sex!' ),
( 'Five-Dollar Footlongs™.' ),
( 'Drinking alone.' ),
( 'Multiple stab wounds.' ),
( 'Soiling oneself.' ),
( 'Child abuse.' ),
( 'Civilian casualties.' ),
( 'Pulling out.' ),
( 'Robert Downey, Jr.' ),
( 'Horse meat.' ),
( 'A really cool hat.' ),
( 'Kim Jong-il.' ),
( 'Jewish fraternities.' ),
( 'The token minority.' ),
( 'Feeding Rosie O`Donnell.' ),
( 'Teaching a robot to love.' ),
( 'A can of whoop-ass.' ),
( 'A windmill full of corpses.' ),
( 'Count Chocula.' ),
( 'Wearing underwear inside-out to avoid doing laundry.' ),
( 'A death ray.' ),
( 'The glass ceiling.' ),
( 'A cooler full of organs.' ),
( 'The American Dream.' ),
( 'Keg stands.' ),
( 'When you fart and a little bit comes out.' ),
( 'Take-backsies.' ),
( 'Dead babies.' ),
( 'Saxophone solos.' ),
( 'Italians.' ),
( 'A fetus.' ),
( 'Dick Cheney.' ),
( 'Amputees.' ),
( 'Eugenics.' ),
( 'My relationship status.' ),
( 'Christopher Walken.' ),
( 'Bees?' ),
( 'Harry Potter erotica.' ),
( 'College.' ),
( 'Getting drunk on mouthwash.' ),
( 'Nazis.' ),
( '8 oz. of sweet Mexican black-tar heroin.' ),
( 'Stephen Hawking talking dirty.' ),
( 'Dead parents.' ),
( 'Object permanence.' ),
( 'Opposable thumbs.' ),
( 'Racially-biased SAT questions.' ),
( 'Jibber-jabber.' ),
( 'Chainsaws for hands.' ),
( 'Nicolas Cage.' ),
( 'Child beauty pageants.' ),
( 'Explosions.' ),
( 'Sniffing glue.' ),
( 'Glenn Beck being harried by a swarm of buzzards.' ),
( 'Repression.' ),
( 'Roofies.' ),
( 'A murder most foul.' ),
( 'Giving 110 percent.' ),
( 'Her Royal Highness, Queen Elizabeth II.' ),
( 'The Trail of Tears.' ),
( 'Being marginalized.' ),
( 'Goblins.' ),
( 'Hope.' ),
( 'The Rev. Dr. Martin Luther King, Jr.' ),
( 'My soul.' ),
( 'A hot mess.' ),
( 'Vikings.' ),
( 'Hot people.' ),
( 'Seduction.' ),
( 'An Oedipus complex.' ),
( 'Geese.' ),
( 'Global warming.' ),
( 'New Age music.' ),
( 'Hot Pockets.' ),
( 'Making a pouty face.' ),
( 'Vehicular manslaughter.' ),
( 'Women`s suffrage.' ),
( 'A defective condom.' ),
( 'Judge Judy.' ),
( 'African children.' ),
( 'The Virginia Tech Massacre.' ),
( 'Barack Obama.' ),
( 'Asians who aren`t good at math.' ),
( 'Elderly Japanese men.' ),
( 'Exchanging pleasantries.' ),
( 'Heteronormativity.' ),
( 'Parting the Red Sea.' ),
( 'Arnold Schwarzenegger.' ),
( 'Road head.' ),
( 'Spectacular abs.' ),
( 'Figgy pudding.' ),
( 'A mopey zoo lion.' ),
( 'A bag of magic beans.' ),
( 'Poor life choices.' ),
( 'My sex life.' ),
( 'Auschwitz.' ),
( 'A thermonuclear detonation.' ),
( 'The Big Bang.' ),
( 'Land mines.' ),
( 'Friends who eat all the snacks.' ),
( 'Goats eating cans.' ),
( 'The Dance of the Sugar Plum Fairy.' ),
( 'Man meat.' ),
( 'Me time.' ),
( 'The Underground Railroad.' ),
( 'Poorly-timed Holocaust jokes.' ),
( 'A sea of troubles.' ),
( 'Lumberjack fantasies.' ),
( 'Morgan Freeman`s voice.' ),
( 'Natural male enhancement.' ),
( 'Being a motherfucking sorcerer.' ),
( 'Passable transvestites.' ),
( 'Sexy pillow fights.' ),
( 'Balls.' ),
( 'Grandma.' ),
( 'Friction.' ),
( 'Party poopers.' ),
( 'Farting and walking away.' ),
( 'Being a dick to children.' ),
( 'Booby-trapping the house to foil burglars.' ),
( 'The Tempur-Pedic Swedish Sleep System™.' ),
( 'Dying.' ),
( 'Hurricane Katrina.' ),
( 'The gays.' ),
( 'The folly of man.' ),
( 'Men.' ),
( 'The Amish.' ),
( 'Pterodactyl eggs.' ),
( 'Team-building exercises.' ),
( 'A brain tumor.' ),
( 'Cards Against Humanity.' ),
( 'Fear itself.' ),
( 'Lady Gaga.' ),
( 'The milk man.' ),
( 'A foul mouth.' ),
( 'A beached whale.' ),
( 'A bloody pacifier.' ),
( 'A crappy little hand.' ),
( 'A low standard of living.' ),
( 'A nuanced critique.' ),
( 'Panty raids.' ),
( 'A passionate Latino lover.' ),
( 'A rival dojo.' ),
( 'A web of lies.' ),
( 'A woman scorned.' ),
( 'Clams.' ),
( 'Apologizing.' ),
( 'Appreciative snapping.' ),
( 'Neil Patrick Harris.' ),
( 'Beating your wives.' ),
( 'Being a dinosaur.' ),
( 'Bosnian chicken farmers.' ),
( 'Nubile slave boys.' ),
( 'Carnies.' ),
( 'Suicidal thoughts.' ),
( 'Dancing with a broom.' ),
( 'Dorito breath.' ),
( 'Eating an albino.' ),
( 'Enormous Scandinavian women.' ),
( 'Fabricating statistics.' ),
( 'Finding a skeleton.' ),
( 'Gandalf.' ),
( 'Genetically engineered super-soldiers.' ),
( 'George Clooney`s musk.' ),
( 'Getting abducted by Peter Pan.' ),
( 'Gladiatorial combat.' ),
( 'Good grammar.' ),
( 'Hipsters.' ),
( 'Historical revisionism.' ),
( 'Insatiable bloodlust.' ),
( 'Jafar.' ),
( 'Jean-Claude Van Damme.' ),
( 'Mad hacky-sack skills.' ),
( 'Leveling up.' ),
( 'Media coverage.' ),
( 'Medieval Times Dinner and Tournament.' ),
( 'Moral ambiguity.' ),
( 'My machete.' ),
( 'One thousand Slim Jims.' ),
( 'Ominous background music.' ),
( 'Overpowering your father.' ),
( 'Pistol-whipping a hostage.' ),
( 'Quiche.' ),
( 'Quivering jowls.' ),
( 'Ryan Gosling riding in on a white horse.' ),
( 'Santa Claus.' ),
( 'Sexual humiliation.' ),
( 'Sexy Siamese twins.' ),
( 'Slow motion.' ),
( 'Space muffins.' ),
( 'Statistically validated stereotypes.' ),
( 'Sudden Poop Explosion Disease.' ),
( 'The economy.' ),
( 'The Fanta girls.' ),
( 'The Gulags.' ),
( 'The harsh light of day.' ),
( 'The hiccups.' ),
( 'The shambling corpse of Larry King.' ),
( 'The four arms of Vishnu.' ),
( 'Being a busy adult with many important things to do.' ),
( 'Words, words, words.' ),
( 'Zeus`s sexual appetites.' );
