DROP TABLE IF EXISTS "player" CASCADE;
CREATE TABLE IF NOT EXISTS "player"(
player_id SERIAL PRIMARY KEY,
username VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL,
email VARCHAR(60) NOT NULL UNIQUE,
score SMALLINT NOT NULL DEFAULT 0,
created_at TIMESTAMP DEFAULT now(),
modified_at TIMESTAMP DEFAULT now(),
CHECK (score >= 0)
);

